# Generated by Django 5.0.6 on 2026-06-25 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hadith', '0001_initial'),
        ('isnad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordFrequencyHadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(db_index=True, max_length=200)),
                ('total_count', models.IntegerField(default=0)),
                ('per_book_distribution', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-total_count'],
            },
        ),
        migrations.CreateModel(
            name='BookGradeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sahih', models.IntegerField(default=0)),
                ('hasan', models.IntegerField(default=0)),
                ('daif', models.IntegerField(default=0)),
                ('maudu', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_stats', to='hadith.book')),
            ],
        ),
        migrations.CreateModel(
            name='NarratorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hadiths', models.IntegerField(default=0)),
                ('books_appeared_in', models.JSONField(default=list)),
                ('teacher_count', models.IntegerField(default=0)),
                ('student_count', models.IntegerField(default=0)),
                ('centrality_score', models.FloatField(default=0.0)),
                ('narrator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='isnad.narrator')),
            ],
            options={
                'ordering': ['-centrality_score'],
            },
        ),
    ]
