# Generated by Django 5.0.6 on 2026-06-25 15:04

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # pg_trgm is required by the GIN trigram indexes below (no-op on non-Postgres).
        TrigramExtension(),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_arabic', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('name_id', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('author_arabic', models.CharField(max_length=200)),
                ('author_death_ah', models.IntegerField(blank=True, null=True)),
                ('collection_type', models.CharField(choices=[('sahih', 'Sahih'), ('sunan', 'Sunan'), ('musnad', 'Musnad'), ('muwatta', 'Muwatta'), ('jami', "Jami'"), ('other', 'Other')], max_length=20)),
                ('total_hadiths', models.IntegerField(default=0)),
                ('grade_summary', models.JSONField(blank=True, default=dict)),
                ('source_api', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title_arabic', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500)),
                ('title_id', models.CharField(blank=True, max_length=500)),
                ('hadith_count', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='hadith.book')),
            ],
            options={
                'ordering': ['book', 'number'],
                'unique_together': {('book', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_book', models.IntegerField()),
                ('global_reference', models.CharField(max_length=100, unique=True)),
                ('alt_reference', models.CharField(blank=True, max_length=100)),
                ('matn_arabic', models.TextField()),
                ('matn_clean', models.TextField(blank=True)),
                ('translation_en', models.TextField(blank=True)),
                ('translation_id', models.TextField(blank=True)),
                ('grade', models.CharField(choices=[('sahih', 'Sahih'), ('hasan', 'Hasan'), ('daif', "Da'if"), ('maudu', "Maudu'"), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('grade_source', models.CharField(blank=True, max_length=200)),
                ('grade_notes', models.TextField(blank=True)),
                ('chain_type', models.CharField(choices=[('muttasil', 'Muttasil (connected)'), ('mursal', 'Mursal (missing companion)'), ('munqati', "Munqati' (broken)"), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('has_parallel', models.BooleanField(default=False)),
                ('source_api', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadiths', to='hadith.book')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hadiths', to='hadith.chapter')),
            ],
            options={
                'ordering': ['book', 'number_in_book'],
            },
        ),
        migrations.CreateModel(
            name='HadithParallel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('hadith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parallels', to='hadith.hadith')),
                ('parallel_hadith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parallel_of', to='hadith.hadith')),
            ],
            options={
                'ordering': ['-similarity_score'],
            },
        ),
        migrations.CreateModel(
            name='HadithQuranRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.IntegerField()),
                ('verse_number', models.IntegerField()),
                ('relevance_type', models.CharField(choices=[('explains', 'Explains'), ('context', 'Context'), ('mentions', 'Mentions')], max_length=20)),
                ('hadith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_refs', to='hadith.hadith')),
            ],
            options={
                'ordering': ['surah_number', 'verse_number'],
            },
        ),
        migrations.AddIndex(
            model_name='hadith',
            index=models.Index(fields=['grade'], name='hadith_hadi_grade_8b4166_idx'),
        ),
        migrations.AddIndex(
            model_name='hadith',
            index=models.Index(fields=['book', 'grade'], name='hadith_hadi_book_id_5670fe_idx'),
        ),
        migrations.AddIndex(
            model_name='hadith',
            index=django.contrib.postgres.indexes.GinIndex(fields=['matn_clean'], name='hadith_matn_clean_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='hadith',
            unique_together={('book', 'number_in_book')},
        ),
        migrations.AlterUniqueTogether(
            name='hadithparallel',
            unique_together={('hadith', 'parallel_hadith')},
        ),
        migrations.AlterUniqueTogether(
            name='hadithquranref',
            unique_together={('hadith', 'surah_number', 'verse_number')},
        ),
    ]
