# Generated by Django 5.0.6 on 2026-06-27 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HadithGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('sahih', 'Sahih'), ('hasan', 'Hasan'), ('daif', "Da'if"), ('maudu', "Maudu'"), ('unknown', 'Unknown')], max_length=20)),
                ('scholar', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('hadith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradings', to='hadith.hadith')),
            ],
            options={
                'ordering': ['scholar'],
                'unique_together': {('hadith', 'scholar')},
            },
        ),
    ]
