# Generated by Django 5.0.6 on 2026-06-27 18:03

from django.db import migrations, models


def backfill_sources(apps, schema_editor):
    """Label existing translations with their known dataset source.

    English came from the fawazahmed0 hadith-api, Indonesian from gadingnst.
    We backfill only rows that actually have a translation, and only where a
    source isn't already set.
    """
    Hadith = apps.get_model("hadith", "Hadith")
    Hadith.objects.exclude(translation_en="").filter(translation_en_source="").update(
        translation_en_source="fawazahmed0 (hadith-api)"
    )
    Hadith.objects.exclude(translation_id="").filter(translation_id_source="").update(
        translation_id_source="hadith.gading.dev (gadingnst)"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0002_hadithgrading'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadith',
            name='translation_en_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hadith',
            name='translation_id_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(backfill_sources, migrations.RunPython.noop),
    ]
