# Generated by Django 5.0.6 on 2026-06-25 15:04

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hadith', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_arabic', models.CharField(max_length=300)),
                ('name_transliteration', models.CharField(max_length=300)),
                ('name_en', models.CharField(max_length=300)),
                ('kunya', models.CharField(blank=True, max_length=200)),
                ('laqab', models.CharField(blank=True, max_length=200)),
                ('nasab', models.CharField(blank=True, max_length=300)),
                ('birth_year_ah', models.IntegerField(blank=True, null=True)),
                ('death_year_ah', models.IntegerField(blank=True, null=True)),
                ('birth_year_ce', models.IntegerField(blank=True, null=True)),
                ('death_year_ce', models.IntegerField(blank=True, null=True)),
                ('generation', models.CharField(choices=[('sahabi', 'Sahabi (Companion)'), ('tabii', "Tabi'i (Successor)"), ('taba_tabii', "Tabi' al-Tabi'in"), ('later', 'Later Generation'), ('collector', 'Hadith Collector'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('reliability_grade', models.CharField(choices=[('thiqah', 'Thiqah (Reliable)'), ('saduq', 'Saduq (Truthful)'), ('daif', "Da'if (Weak)"), ('majhul', 'Majhul (Unknown)'), ('matruk', 'Matruk (Abandoned)'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('reliability_notes', models.TextField(blank=True)),
                ('bio_source', models.CharField(blank=True, max_length=200)),
                ('total_hadiths', models.IntegerField(default=0)),
                ('centrality_score', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['name_transliteration'],
                'indexes': [models.Index(fields=['generation'], name='isnad_narra_generat_2905db_idx'), models.Index(fields=['reliability_grade'], name='isnad_narra_reliabi_733777_idx'), models.Index(fields=['-centrality_score'], name='isnad_narra_central_19be17_idx'), django.contrib.postgres.indexes.GinIndex(fields=['name_arabic'], name='narrator_name_ar_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='Sanad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_text_arabic', models.TextField()),
                ('chain_text_en', models.TextField(blank=True)),
                ('chain_order', models.JSONField(default=list)),
                ('hadith', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sanad', to='hadith.hadith')),
            ],
        ),
        migrations.CreateModel(
            name='HadithNarrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('hadith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain', to='hadith.hadith')),
                ('narrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='isnad.narrator')),
            ],
            options={
                'ordering': ['hadith', 'position'],
                'unique_together': {('hadith', 'narrator', 'position')},
            },
        ),
        migrations.CreateModel(
            name='NarratorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hadith_count', models.IntegerField(default=1)),
                ('book_ids', models.JSONField(default=list)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='isnad.narrator')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='isnad.narrator')),
            ],
            options={
                'indexes': [models.Index(fields=['teacher'], name='isnad_narra_teacher_d63ca8_idx'), models.Index(fields=['student'], name='isnad_narra_student_527daf_idx')],
                'unique_together': {('teacher', 'student')},
            },
        ),
    ]
