# Generated by Django 5.0.6 on 2026-06-25 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hadith', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=200)),
                ('name_id', models.CharField(blank=True, max_length=200)),
                ('name_arabic', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='HadithTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.FloatField(default=1.0)),
                ('hadith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='hadith.hadith')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadiths', to='semantic.topic')),
            ],
            options={
                'ordering': ['-relevance'],
                'unique_together': {('hadith', 'topic')},
            },
        ),
    ]
